### ISSUE TITLE
docs(idea/package): Suteraの動的オブジェクトとweb assemblyについて

### ISSUE THREAD

**Issue by LegitYew0108** [SuteraVR/Specifications#13]

**Comment by LegitYew0108** [comment]
## 目的
Suteraが動的オブジェクトの形式として、なぜwasmを利用しているのかを文書化する。

## 内容
ざっくりと、なんでweb assemblyを採用するに至った背景を書きます

#20 に絡めて、様々な環境でスクリプト実行できないと動的なオブジェクトは作れないよね
⇨Unity C#とか、Godot GDScript見たいな環境に依存している言語形式じゃダメだよね
⇨じゃあ、サンドボックス環境で実行できて、かつ色んなプラットフォームにも対応できる形式にしたい！
⇨web assemblyを使おう！
という流れです

**Comment by AsPulse** [comment]
なぜサンドボックスじゃないとだめか (補足)
最初はそうしない形式をいっぱい考えたけど、それだとワールドをダウンロードすることが実行ファイルをダウンロードすることと同じになっちゃう
「SuteraVRのワールドに入ったらウイルスに感染したんだけど！」みたいな事態を避けたい
Suteraパッケージ(ワールドやアバター)がHTTP通信を飛ばすとき、ローカルのディスクにアクセスしようとするとき等はユーザーに確認を取りたい

**Comment by See2et** [comment]
closed by #74
