### ISSUE TITLE
docs(idea/core): SuteraVRのゲームエンジンの利用方針

### ISSUE THREAD

**Issue by LegitYew0108** [SuteraVR/Specifications#16]

**Comment by See2et** [comment]
SuteraVRは、特定の団体に依存したくないという思いを元に開発がスタートしました！
同じようにゲームエンジンにも依存したくない...よねっ！

**Comment by LegitYew0108** [comment]
No ゲームエンジン依存！のために、
- ゲームエンジンは描画エンジンとしてのみ使います
- 動的なオブジェクトはwasmを使い、様々なプラットフォーム対応を目指します（参照： #13 
- Sutera VR Organizationの側は公式の提供する実装として、Vanilla Clientのみ実装する（参照： #20
