### ISSUE TITLE
docs(idea/object-storage): Object-Storageの役割について

### ISSUE THREAD

**Issue by See2et** [SuteraVR/Specifications#17]

**Comment by tukiminya** [comment]
@AsPulse Request Summary!

**Comment by AsPulse** [comment]
- 非ユーザー依存データを保存する
  -  非ユーザー依存データそのものについては #18 で述べられるので触れなくてよい
- Suteraネットワーク内のObject-Storageコンポーネントのうち、自動的に複数箇所へと保管される
- もしBloomが死んだら、データを持っている他のものから埋め戻す (ネットワーク内で一定数の複製を保つ)  
- 大事なワールドとかのコピーは指定の(self-hostedの)Bloomに持たせるという運用もできる
  - まれ、かつ仕方ないことではあるけど、同じデータの複製を持ってる全てのbloomが同時にinactiveになるとデータのロストがありえる
