### ISSUE TITLE
docs(idea/sutera): なぜHTTPにこだわるか

### ISSUE THREAD

**Issue by AsPulse** [SuteraVR/Specifications#23]

**Comment by tukiminya** [comment]
@AsPulse Request Summary!

**Comment by AsPulse** [comment]
@tukiminya 
- TCPやWebSocketを使うのは最低限 (Clocking-Serverのみ)
- 基本的に、ペイロード(body size) の小さいHTTP通信を基盤とする
- Why?
  - Cloudflare Zero Trust, Google Cloud Runのような環境ではしばしばHTTP通信のみが対応している
  - これらはめちゃくちゃ安い。常時起動せず、リクエストが起動したときだけ反応すればいい
  - Suteraネットワークにおいて、Bloomを個人が気軽に建てれるということはめちゃくちゃ大事
  - HTTPはHostnameでリクエストの振り分けができて、一つのポート番号の奥に複数のサービスを建てられる貴重なプロトコルでもある
