### ISSUE TITLE
docs(idea/sutera): なぜべき等性を保たなければいけないのか

### ISSUE THREAD

**Issue by See2et** [SuteraVR/Specifications#30]

**Comment by See2et** [comment]
sutera/11-*****.md

**Comment by See2et** [comment]
Suteraは個人を認証する要素として電子署名を採用している訳なんだけれど...

べき等性を保たないとリプレイ攻撃に挙げられるような他人に成り済ました操作ができてしまうんだ

そのようなことを避けるために、べき等性を保つんだね

@AsPulse たぶんアバウトなので補足ほしいです！

参考になりそうな画像↓
![Image](https://github.com/user-attachments/assets/44fc109a-62f9-432b-bf5c-33b1eaafbd42)

**Comment by slotsu0809** [comment]
@AsPulse
